### ISSUE TITLE
проблема

### ISSUE THREAD

**Issue by Lightning-py** [portasynthinca3/obsidianmd-mtuci-timetable#1]
у меня проблема. Я  хорошо покушал, потом захотел поспать и уснул, так и не сделав домашку. что делать?

**Comment by portasynthinca3** [comment]
к сожалению, этот плагин не может тебе с этим помочь :(

**Comment by Lightning-py** [comment]
блиииииин :(((((((((((((((((((

**Comment by portasynthinca3** [comment]
многие студенты сталкиваются с данной проблемой

**Comment by Lightning-py** [comment]
почему?

**Comment by Lightning-py** [comment]
какого хуя ты открыл этот ебаный ишью, лучше бы сука свой рот открывал почаще
